# Generated by Django 5.2.3 on 2025-06-27 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pcb_manager', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='device',
            old_name='image_filename',
            new_name='image',
        ),
    ]
